Replace slider
AdvisorySG/dawn-advisory-theme pull request #108
Opened 2022-04-23 06:59 UTC by Hackin7

![image](https://user-images.githubusercontent.com/18213722/164883973-a0876e67-b41d-4131-a3f0-993210a0b975.png)

2022-04-23 07:00 UTC, Hackin7 commented
Also happened to change the carousel for the featured to GliderJS

Code in default.hbs, can be moved to a partial soon

Need to confirm the design

2022-05-08 10:41 UTC, wei2912 reviewed
Code looks fine overall, but please delete all references to OWL carousel (and the respective files). Also, it seems that `package-lock.json` wasn't updated. Do fix the conflict!

Please make further changes based on @BenitaWZX's remarks on aesthetics of footer (regarding distance between title and logos). Otherwise, I think it's good to go - frankly the aesthetics of this won't be great, but so long as it shows up I think it's alright.

2022-05-12 01:01 UTC, Hackin7 commented
![image](https://user-images.githubusercontent.com/18213722/167971240-2d0e37c6-e9dc-4681-ba65-b12fc70007ba.png)

Added the padding, and should have removed js and CSS files of owl carousel

Additionally separated the sliders into separate componenets

2022-05-14 06:56 UTC, wei2912 requested changes
No other comments wrt aesthetics, will let @BenitaWZX comment further. Once that's done, I'll review the code.

2022-05-14 06:56 UTC, wei2912 commented on default.hbs
> +        {{> featured-by}}
These two should be placed just on the homepage (`home.hbs`), not in every page.

2022-05-14 11:46 UTC, wei2912 commented
Merged in https://github.com/AdvisorySG/dawn-advisory-theme/commit/dbc152e78ef4c78ebb611ad2fb338ca883f0bfec.

2022-05-14 11:46 UTC, closed without merging