Secondary tags listing
AdvisorySG/dawn-advisory-theme pull request #21
Opened 2021-11-22 16:44 UTC by Hackin7

![image](https://user-images.githubusercontent.com/18213722/142900804-ea038323-cb64-44ab-b623-59f0f6f6e3e4.png)

I tried making a list of the secondary tags right below the primary tag, above the title. I believe this way makes more sense compared to putting the tags at the bottom of the article so that the reader can get an idea of what to expect in the article

2021-12-10 13:28 UTC, wei2912 commented
As discussed, secondary tags should be added in a similar fashion to the "More:" part here:

![image](https://user-images.githubusercontent.com/2070423/145581335-f7c81aa6-544e-42c3-8f3b-f7c7962effa7.png)

(without the `#`s)

2021-12-13 09:21 UTC, wei2912 requested changes
See above comments.

2021-12-19 10:02 UTC, Hackin7 commented
![image](https://user-images.githubusercontent.com/18213722/146670944-6536d509-b3da-4d61-862a-dbd533eee3aa.png)
![image](https://user-images.githubusercontent.com/18213722/146670957-16c09d72-f390-4942-99e2-37790f0cc7bc.png)

I tried making the secondary tag size smaller but I think it may be too hard to read

![image](https://user-images.githubusercontent.com/18213722/146671010-911d32fa-d071-4af2-a555-d3467588ce5a.png)

2021-12-26 07:58 UTC, wei2912 commented
Just a few comments:

1.Articles with no tags show up like this. Could we just hide the line entirely?

![image](https://user-images.githubusercontent.com/2070423/147402010-a8bcac1b-f3c3-44ba-8e57-0a20038de54e.png)

2. Design wise I think they look good, although long tags might be a bit of an issue. But I think it's fine to go for now.

2021-12-26 07:59 UTC, wei2912 requested changes
See above.

2021-12-30 14:03 UTC, Hackin7 commented
Kind of managed to solve it 

![image](https://user-images.githubusercontent.com/18213722/147758649-ae71cf65-e18a-4410-a4ca-2ca0b7541b4d.png)

However I found a weird issue

![image](https://user-images.githubusercontent.com/18213722/147758441-9399b972-ebec-45ad-810d-e06b4ce5fa9c.png)

In this case it does not even have a primary tag (ghost doesn't recognise that it has a primary tag), even though the tag distribution is as such

![image](https://user-images.githubusercontent.com/18213722/147758554-2ab0fc26-cad2-44d5-b8e9-badbddbae67c.png)

with my current patch it shouldn't be too much of an issue, just kind of weird that some articles don't have primary tags

2021-12-31 11:19 UTC, wei2912 commented
@Hackin7 Thanks for pointing that out - think it's not really a big issue. I'll make sure to write in the post guide that the first tag should be an external tag.

2022-01-01 13:50 UTC, wei2912 commented on partials/content.hbs
> +
Please delete this blank line!

2022-01-01 13:51 UTC, wei2912 requested changes
LGTM, other than one small change.

2022-01-01 14:07 UTC, wei2912 commented
Merged in https://github.com/AdvisorySG/dawn-advisory-theme/commit/ccace997ede6ac0724b7f034fe12a47009dfe920.

2022-01-01 14:07 UTC, closed without merging