Pagination for search
AdvisorySG/dawn-advisory-theme pull request #228
Opened 2023-04-09 16:13 UTC by gajinkee

Added the pagination. I think it looks pretty good.
Also fixed a bug where clearing input with the x button doesn't reset the search.

![ss1](https://user-images.githubusercontent.com/29113994/230783781-5a3cc751-aaf5-4dbd-9f5a-03a42bd3248e.png)
![ss2](https://user-images.githubusercontent.com/29113994/230783785-1f43e26c-b3da-4c82-acaf-c946612c7d98.png)
![ss3](https://user-images.githubusercontent.com/29113994/230783790-daddcd34-719d-4ffe-9de9-4131d39727e1.png)

2023-04-11 14:41 UTC, wei2912 commented
1. Remove pagination bar when empty, have visual indicator to disable buttons if there's no left/right page
2. Vertically align "Showing … results" with the left/right buttons.
3. On mobile, the "Showing … results" and left/right buttons should still be on the same row.
4. Remove scrolling where possible (but for mobile it's fine)
5. Increase font size and modal window size for desktop, fix modal size

2023-04-13 10:15 UTC, gajinkee commented
Made all the changes mentioned. Works better for mobile now too. Will demo at the next meeting.

![ss1](https://user-images.githubusercontent.com/29113994/231727879-757b429a-69f1-42ce-9100-56d9f66c2cc6.png)
![ss2](https://user-images.githubusercontent.com/29113994/231727888-bc59821d-c1da-466f-bfbc-4326b367c21e.png)

2023-05-10 01:45 UTC, wei2912 requested changes
Have left some minor remarks. Besides the below comments,
1. Could the pagination buttons be greyed out and disabled if there is no prev/next page of results?
2. Ideally the scrollbar for the results should not appear, and the height of the results modal should be fixed (so that the positioning of the searchbar and buttons don't change for each page).

I will review the JS code closely when the above changes have been made.

2023-05-10 01:45 UTC, wei2912 commented on assets/css/site/modal.css
> +    height: 54%;
Can we increase the height further to 80%?

2023-05-22 11:35 UTC, wei2912 commented
Functionally, I think this is ready for merge. There are a few other issues to be addressed to improve the design:

1. I think there needs to be some more changes made to ensure the search feature is responsive on mobile:

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/2070423/4ab5e378-923d-441e-896e-930536086369)

2. Longer post titles are not handled well:

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/2070423/239a42ad-7e52-42df-a0d6-51895fee8d24)

3. 7 is a strange number for no. of results, 5 may work better.

2023-05-22 12:26 UTC, merged

2023-05-22 12:28 UTC, wei2912 commented
(3) has been addressed in https://github.com/AdvisorySG/dawn-advisory-theme/pull/228/commits/8d886a3012074672e715b64b8d8fd2448379678d.